# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: todo_group_name
  joint_model_group_pose: todo_state_name
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - virtual_joint
    - movable_camera_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
multi_dof_joint_trajectory_action:
  type: MultiDofFollowJointTrajectory
  joints:
    - virtual_joint/trans_x
    - virtual_joint/trans_y
    - virtual_joint/trans_z
    - virtual_joint/rot_x
    - virtual_joint/rot_y
    - virtual_joint/rot_z
    - virtual_joint/rot_w
  gains:
    virtual_joint/trans_x:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    virtual_joint/trans_y:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    virtual_joint/trans_z:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    virtual_joint/rot_x:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    virtual_joint/rot_y:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    virtual_joint/rot_z:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    virtual_joint/rot_w:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
movable_camera_joint_controller:
  type: position_controllers/JointPositionController
  joints:
    movable_camera_joint
  gains:
    movable_camera_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1